// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVs1omYIqgdwgW_1iEPefRSmboIrphLeo',
    appId: '1:218594299580:web:08708f20fab0e616ec4ab9',
    messagingSenderId: '218594299580',
    projectId: 'myprayer-e365a',
    authDomain: 'myprayer-e365a.firebaseapp.com',
    storageBucket: 'myprayer-e365a.firebasestorage.app',
    measurementId: 'G-8KJ7YN1K57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlxR1tMtmF8Dxee_PIdKqm2gT02JT2it4',
    appId: '1:218594299580:android:f5c56d1acd016985ec4ab9',
    messagingSenderId: '218594299580',
    projectId: 'myprayer-e365a',
    storageBucket: 'myprayer-e365a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdFujzOhqEmWQzw3G1ve-v35_gn_7rndw',
    appId: '1:218594299580:ios:817ae66084f8b5b8ec4ab9',
    messagingSenderId: '218594299580',
    projectId: 'myprayer-e365a',
    storageBucket: 'myprayer-e365a.firebasestorage.app',
    iosBundleId: 'com.example.priere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdFujzOhqEmWQzw3G1ve-v35_gn_7rndw',
    appId: '1:218594299580:ios:817ae66084f8b5b8ec4ab9',
    messagingSenderId: '218594299580',
    projectId: 'myprayer-e365a',
    storageBucket: 'myprayer-e365a.firebasestorage.app',
    iosBundleId: 'com.example.priere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVs1omYIqgdwgW_1iEPefRSmboIrphLeo',
    appId: '1:218594299580:web:9066927ae217d5c5ec4ab9',
    messagingSenderId: '218594299580',
    projectId: 'myprayer-e365a',
    authDomain: 'myprayer-e365a.firebaseapp.com',
    storageBucket: 'myprayer-e365a.firebasestorage.app',
    measurementId: 'G-8PK9TX85WF',
  );

}